openapi: 3.0.0
info:
  title: Voting system
  description: Swagger documentation for voting system from soutoukakka
  version: 1.0.0
servers:
  - url: http://localhost:1234
    description: development